# Generated by Django 5.0.14 on 2026-07-05 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pqr", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="pqr",
            name="calificacion",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pqr",
            name="comentario_calificacion",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="pqr",
            name="fecha_limite",
            field=models.DateField(blank=True, editable=False, null=True),
        ),
    ]
